name: Run test-cases
on: [pull_request]

jobs:
  my_job:
    runs-on: ubuntu-latest

    steps:
    - name: Keploy Report
      uses: keploy/testgpt@main
      with:
        working-directory: ./
        delay: 10
        command: docker compose up
        keploy-path: ./
